# Define constants for pin numbers
DISPLAY_SCK_PIN = 14
DISPLAY_MOSI_PIN = 13
DISPLAY_CS_PIN = 15
DISPLAY_DC_PIN = 2
DISPLAY_RST_PIN = 15
TOUCHSCREEN_SCK_PIN = 25
TOUCHSCREEN_MOSI_PIN = 32
TOUCHSCREEN_MISO_PIN = 39
TOUCHSCREEN_CS_PIN = 33
TOUCHSCREEN_INT_PIN = 36
BACKLIGHT_PIN = 21
